name: Run ETL_Pipeline-Maria-Irfan-DS-032-2023
  push:
    paths:
      - '**.ipynb'
      - '**.py'
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas notebook nbconvert

    - name: Run ETL Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace ETL_ASSIGNMENT.ipynb

    - name: Save CSV as GitHub artifact
      uses: actions/upload-artifact@v3
      with:
        name: cleaned-data
        path: cleaned_weather_data.csv
